# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftTestEmpty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxCocoa'
  # Pods for RxSwiftTestEmpty

  target 'RxSwiftTestEmptyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftTestEmptyUITests' do
    # Pods for testing
  end

end
